#!/bin/bash

# automatically renumber tmux windows
set -g renumber-windows on

# If on, display a message instead of sending a bell when activity occurs in a window for which the
# monitor-activity window option is enabled.  If set to both, a bell and a message are produced.
set -g visual-activity off

# Aggressively resize the chosen window.  This means that tmux will resize the window to the size of the
# smallest or largest session (see the window-size option) for which it is the current window, rather
# than the session to which it is attached.
setw -g aggressive-resize on

# set vi mode for copy mode
setw -g mode-keys vi

######################
#### Key Bindings ####
######################

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# pane movement shortcuts
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'dracula/tmux'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
