#!/bin/bash

# tmux display things in 256 colors
set -g default-terminal "tmux-256color"
# set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'
# set -g default-terminal "rxvt-unicode-256color"

set -g history-limit 10000

set-option -g focus-events on

set-option -sa terminal-overrides ',xterm-256color:RGB'

# extend length of session name
set -g status-left-length 30

# automatically renumber tmux windows
set -g renumber-windows on

# Activity Monitoring
# Monitor for activity in the window.  Windows with activity are highlighted in the status line.
setw -g monitor-activity on

# If on, display a message instead of sending a bell when activity occurs in a window for which the
# monitor-activity window option is enabled.  If set to both, a bell and a message are produced.
set -g visual-activity off

# Aggressively resize the chosen window.  This means that tmux will resize the window to the size of the
# smallest or largest session (see the window-size option) for which it is the current window, rather
# than the session to which it is attached.
setw -g aggressive-resize on

# Set the time in milliseconds for which tmux waits after an escape is input to determine if it is part
# of a function or meta key sequences.  The default is 500 milliseconds.
set -sg escape-time 0

# enable mouse support for switching panes/windows
setw -g mouse on

# set vi mode for copy mode
setw -g mode-keys vi

######################
#### Key Bindings ####
######################

# set panes and new windows to use CWD
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# reload config file
bind C source-file ~/.tmux.conf \; display "Config Reloaded!"

# synchronize all panes in a window
bind y setw synchronize-panes

# pane movement shortcuts
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "xsel --clipboard --input"

##############################
### Color & Style Settings ###
##############################

white='#f8f8f2'
gray='#44475a'
dark_gray='#282a36'
light_purple='#bd93f9'
dark_purple='#6272a4'
cyan='#8be9fd'
green='#50fa7b'
orange='#ffb86c'
red='#ff5555'
pink='#ff79c6'
yellow='#f1fa8c'

set-option -g status-style bg=default,fg=$green

# pane border colors
set-option -g pane-active-border-style fg=$pink
set-option -g pane-border-style fg=$pink

# pane number display
set-option -g display-panes-active-colour $light_purple
