#!/bin/bash

# https://github.com/tmux/tmux/issues/224#issuecomment-161332667
set -ag terminal-overrides ',*:cud1=\E[1B'

# automatically renumber tmux windows
set -g renumber-windows on

# If on, display a message instead of sending a bell when activity occurs in a window for which the
# monitor-activity window option is enabled.  If set to both, a bell and a message are produced.
set -g visual-activity off

# Aggressively resize the chosen window.  This means that tmux will resize the window to the size of the
# smallest or largest session (see the window-size option) for which it is the current window, rather
# than the session to which it is attached.
setw -g aggressive-resize on

# set vi mode for copy mode
setw -g mode-keys vi

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# List of plugins (https://github.com/tmux-plugins/list)
set -g @plugin 'tmux-plugins/tpm'  # https://github.com/tmux-plugins/tpm?tab=readme-ov-file
set -g @plugin 'tmux-plugins/tmux-sensible'  # https://github.com/tmux-plugins/tmux-sensible
set -g @plugin 'tmux-plugins/tmux-pain-control'  # https://github.com/tmux-plugins/tmux-pain-control

# https://github.com/dracula/tmux/blob/master/docs/CONFIG.md
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "time"
set -g @dracula-show-left-icon "#h | #S"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$HOME/.tmux/plugins/tpm/tpm"
